import bedsImage from '../assets/images/beds.jpeg';
import foodImage from '../assets/images/food.jpeg';
import toysImage from '../assets/images/toys.jpeg';
import accessoriesImage from '../assets/images/accessories.jpeg';

export const dogProducts = [
  {
    id: 1,
    name: 'Dry Dog Food(Chicken Flavor)',
    brand: 'Pawsome Eats',
    size: 20,
    sizeType: 'lbs',
    price: 29.99,
    img_url: 'https://m.media-amazon.com/images/I/81R8Xul9U+L._AC_SL1500_.jpg',
    quantity: 1,
    shopName: 'PetCo',
    discountPercentage: 5,
    rating: 4.7,
  },
  {
    id: 2,
    name: 'Wet Dog Food(Beef Stew)',
    brand: 'Tasty Tails',
    size: 12,
    sizeType: 'cans',
    price: 18.99,
    img_url:
      'https://www.ivorycoat.com.au/cdn/shop/products/IC_AU_400G_ADULTDOG_GF_BEEFSTEW_01_MOI_1200x1200_crop_center.jpg?v=1645560742',
    quantity: 1,
    shopName: 'PetSmart',
    discountPercentage: 10,
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Grain-Free Dog Food(Salmon Recipe)',
    brand: 'Natural Paws',
    size: 15,
    sizeType: 'lbs',
    price: 34.99,
    img_url:
      'https://www.chico.ca/wp-content/uploads/2023/10/Design-sans-titre4-2.jpeg',
    quantity: 1,
    shopName: 'Petland',
    discountPercentage: 15,
    rating: 4.5,
  },
  {
    id: 4,
    name: 'Puppy Food(Lamb Formula)',
    brand: 'Healthy Hounds',
    size: 10,
    sizeType: 'lbs',
    price: 22.99,
    img_url:
      'https://m.media-amazon.com/images/I/81mTKlWyGoL._AC_UF1000,1000_QL80_.jpg',
    quantity: 1,
    shopName: 'Pet Supplies Plus',
    discountPercentage: 8,
    rating: 4.2,
  },
  {
    id: 5,
    name: 'Senior Dog Food(Chicken and Brown Rice)',
    brand: 'Elderly Paws',
    size: 25,
    sizeType: 'lbs',
    price: 39.99,
    img_url:
      'https://www.cuddlespetstore.com/img/product/burns-chicken-brown-rice-senior-12kg-6008093-1600.jpg',
    quantity: 1,
    shopName: 'Pet Kingdom',
    discountPercentage: 12,
    rating: 4.6,
  },
  {
    id: 6,
    name: 'Squeaky Plush Toy',
    brand: 'Happy Paws',
    sizeType: 'Medium',
    price: 7.99,
    img_url: 'https://m.media-amazon.com/images/I/61oDok6j8mS._AC_SL1500_.jpg',
    quantity: 1,
    shopName: 'PetSmart',
    discountPercentage: 20,
    rating: 4.9,
  },
  {
    id: 7,
    name: 'Rubber Chew Bone',
    brand: 'ChewMaster',
    sizeType: 'Large',
    price: 9.49,
    img_url: 'https://m.media-amazon.com/images/I/61NZu7+sMuL.jpg',
    quantity: 1,
    shopName: 'PetCo',
    discountPercentage: 18,
    rating: 4.4,
  },
  {
    id: 8,
    name: 'Interactive Ball Toy',
    brand: 'Playful Pets',
    sizeType: 'Small',
    price: 5.99,
    img_url: 'https://m.media-amazon.com/images/I/61-EGk+lh8L.jpg',
    quantity: 1,
    shopName: 'Pet Supplies Plus',
    discountPercentage: 15,
    rating: 4.7,
  },
  {
    id: 9,
    name: 'Tug-of-War Rope Toy',
    brand: 'Strong Paws',
    sizeType: 'Small',
    price: 11.99,
    img_url: 'https://m.media-amazon.com/images/I/81TMtFShCgL.jpg',
    quantity: 1,
    shopName: 'Pet Kingdom',
    discountPercentage: 10,
    rating: 4.3,
  },
  {
    id: 10,
    name: 'Chewable Rubber Ring',
    brand: 'Durable Chew',
    sizeType: 'Small',
    price: 6.99,
    img_url:
      'https://m.media-amazon.com/images/I/71V2US6aDGS._AC_UF350,350_QL80_.jpg',
    quantity: 1,
    shopName: 'Petland',
    discountPercentage: 25,
    rating: 4.8,
  },
];

export const categories = [
  {
    id: 1,
    name: 'Beds',
    img_uri: bedsImage,
  },
  {
    id: 2,
    name: 'Food',
    img_uri: foodImage,
  },
  {
    id: 3,
    name: 'Toys',
    img_uri: toysImage,
  },
  {
    id: 4,
    name: 'Accessories',
    img_uri: accessoriesImage,
  },
];
